project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Labs.qmd
        text: Labs
      - href: Projects.qmd
        text: Projects
      - href: Presentations.qmd
        text: Presentations
        
      

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

