project:
  type: website
  output-dir: docs

site-url: https://mishellele.github.io/Michelle
base-url: /my-quarto-site/

website:
  title: "Michelle Le"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Labs.qmd
        text: Labs
      - href: Projects.qmd
        text: Projects
      - href: Presentations.qmd
        text: Presentations

        
      

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

