project:
  type: website
  output-dir: docs

website:
  title: "Michelle Le"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Labs.qmd
        text: Labs
      - href: Projects.qmd
        text: Projects
      - href: Presentations.qmd
        text: Presentations

        
      

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    embed-resources: true

editor: visual

